-- Walls as first-class layout entities
-- Promotes walls from free-floating architectural_elements rows into a
-- proper line-segment table so the renderer can extrude them into 3D and
-- snap items to wall faces. Architectural elements gain optional wall
-- attachment so doors/windows can sit on a wall and be rendered as
-- openings rather than free-floating boxes.
--
-- Run after supabase-belongings-placement.sql.

CREATE TABLE IF NOT EXISTS walls (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  floor_plan_id BIGINT NOT NULL REFERENCES home_floor_plans(id) ON DELETE CASCADE,
  start_x_ft NUMERIC NOT NULL,
  start_y_ft NUMERIC NOT NULL,
  end_x_ft NUMERIC NOT NULL,
  end_y_ft NUMERIC NOT NULL,
  thickness_in NUMERIC NOT NULL DEFAULT 5,
  height_ft NUMERIC,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS walls_floor_plan_id_idx ON walls(floor_plan_id);

ALTER TABLE walls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS walls_authenticated_all ON walls;
CREATE POLICY walls_authenticated_all
  ON walls FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

ALTER TABLE architectural_elements ADD COLUMN IF NOT EXISTS wall_id BIGINT;
ALTER TABLE architectural_elements ADD COLUMN IF NOT EXISTS offset_along_wall_ft NUMERIC;

ALTER TABLE architectural_elements
  DROP CONSTRAINT IF EXISTS architectural_elements_wall_id_fkey;
ALTER TABLE architectural_elements
  ADD CONSTRAINT architectural_elements_wall_id_fkey
  FOREIGN KEY (wall_id) REFERENCES walls(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS architectural_elements_wall_id_idx
  ON architectural_elements(wall_id)
  WHERE wall_id IS NOT NULL;
