-- CREATE TABLES
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  earliestMoveDate TEXT NOT NULL,
  latestMoveDate TEXT NOT NULL,
  confirmedMoveDate TEXT,
  closingDate TEXT
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  orderIndex INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  categoryId BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('Not Started', 'In Progress', 'Complete')),
  owner TEXT NOT NULL CHECK (owner IN ('Andrew', 'Tory', 'Both')),
  phase TEXT NOT NULL DEFAULT 'Both' CHECK (phase IN ('Move Out', 'Move In', 'Both')),
  dueDate TEXT,
  completionDate TEXT,
  scheduledEventDate TEXT,
  scheduledEventTimeWindow TEXT,
  notes TEXT,
  orderIndex INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS packing_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room TEXT NOT NULL,
  item_name TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('Bring', 'Trash', 'Sell', 'Donate')),
  status TEXT NOT NULL DEFAULT 'Unresolved' CHECK (status IN ('Unresolved', 'Resolved')),
  notes TEXT,
  priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High')),
  created_at TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  taskId BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  categoryId BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  isLink BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  notes TEXT,
  category TEXT NOT NULL CHECK (category IN ('Origin', 'Destination', 'Stop', 'Utility', 'Errand', 'Service')),
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  "createdAt" TEXT NOT NULL
);

-- SEED LOCATIONS
INSERT INTO locations (name, address, category, lat, lng, "createdAt")
VALUES 
  ('805 S Hercules St', '805 S Hercules St, Clearwater, FL 33764', 'Origin', 27.9546, -82.7533, '2026-04-16T00:00:00Z'),
  ('25 Chestnut Street', '25 Chestnut Street, Cold Spring, NY 10516', 'Destination', 41.4190, -73.9554, '2026-04-16T00:00:00Z')
ON CONFLICT DO NOTHING;
INSERT INTO settings (id, earliestMoveDate, latestMoveDate)
VALUES (1, '2026-06-15', '2026-07-01')
ON CONFLICT (id) DO NOTHING;

-- Seed categories and return IDs
WITH inserted_cats AS (
  INSERT INTO categories (name, orderIndex)
  VALUES 
    ('Move-Out Logistics', 0),
    ('Move-In Setup', 1),
    ('Packing & Supplies', 2),
    ('Travel Planning', 3),
    ('Utilities Setup & Cancellation', 4),
    ('Address Changes', 5),
    ('Financial & Banking Updates', 6),
    ('Insurance', 7),
    ('Medical & Pharmacy', 8),
    ('Pets', 9),
    ('Home Purchases & Setup', 10),
    ('Closing & Contract', 11),
    ('Cold Spring Local Setup', 12)
  RETURNING id, name
)
INSERT INTO tasks (categoryId, title, status, owner, timingType, timingOffsetDays, orderIndex)
SELECT 
  ic.id, t.title, 'Not Started', t.owner, t.timingType, t.timingOffsetDays, t.orderIndex
FROM inserted_cats ic
JOIN (
  VALUES 
    ('Move-Out Logistics', 'Book PODS', 'Both', 'Before Move', -60, 0),
    ('Move-Out Logistics', 'Schedule pod delivery', 'Andrew', 'Before Move', -30, 1),
    ('Move-Out Logistics', 'Schedule move-out help', 'Both', 'Before Move', -14, 2),
    ('Packing & Supplies', 'Buy clear containers', 'Tory', 'Before Move', -45, 0),
    ('Packing & Supplies', 'Create packing plan', 'Both', 'Before Move', -40, 1),
    ('Travel Planning', 'Plan route', 'Both', 'Before Move', -30, 0),
    ('Travel Planning', 'Plan accommodations', 'Andrew', 'Before Move', -25, 1),
    ('Utilities Setup & Cancellation', 'Cancel utilities (Clearwater)', 'Andrew', 'Before Move', -7, 0),
    ('Utilities Setup & Cancellation', 'Setup utilities (Cold Spring)', 'Tory', 'Before Move', -7, 1),
    ('Address Changes', 'Forward mail', 'Both', 'Before Move', -5, 0),
    ('Closing & Contract', 'Final walkthrough', 'Both', 'Before Closing', -1, 0),
    ('Closing & Contract', 'Sign closing docs', 'Both', 'Before Closing', 0, 1),
    ('Cold Spring Local Setup', 'Setup NYSEG (Electric)', 'Andrew', 'After Move', 1, 0),
    ('Cold Spring Local Setup', 'Setup Village Water Dept', 'Tory', 'After Move', 1, 1),
    ('Cold Spring Local Setup', 'Check Optimum/Verizon for Internet', 'Both', 'After Move', 2, 2)
) AS t(cat_name, title, owner, timingType, timingOffsetDays, orderIndex)
ON ic.name = t.cat_name;
