-- Home planning expansion
-- Run after the existing schema + migration scripts.

-- Reconcile task owner to match current app behavior.
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_owner_check;
ALTER TABLE tasks ALTER COLUMN owner DROP NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_owner_check
  CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory'));

-- Replace legacy documents table with a generic attachment model.
DROP TABLE IF EXISTS documents CASCADE;

CREATE TABLE IF NOT EXISTS tracks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  color TEXT,
  icon TEXT,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS timeline_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  entry_type TEXT NOT NULL DEFAULT 'event',
  status TEXT NOT NULL DEFAULT 'estimated',
  date TEXT NOT NULL,
  time TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS planning_tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  section TEXT NOT NULL DEFAULT 'purchase',
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Not Started',
  owner TEXT,
  due_date TEXT,
  completed_at TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT planning_tasks_status_check CHECK (status IN ('Not Started', 'In Progress', 'Complete')),
  CONSTRAINT planning_tasks_owner_check CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory')),
  CONSTRAINT planning_tasks_section_check CHECK (section IN ('purchase', 'loan', 'home_setup', 'updates'))
);

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  floor TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS room_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  belonging_id BIGINT REFERENCES belongings(id) ON DELETE SET NULL,
  item_name TEXT NOT NULL,
  item_source TEXT NOT NULL DEFAULT 'planned_purchase',
  status TEXT NOT NULL DEFAULT 'planned',
  dimensions TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT room_items_source_check CHECK (item_source IN ('existing_belonging', 'planned_purchase')),
  CONSTRAINT room_items_status_check CHECK (status IN ('planned', 'placed', 'undecided'))
);

ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_x NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_y NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_w NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_h NUMERIC;

CREATE TABLE IF NOT EXISTS home_projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  area TEXT,
  status TEXT NOT NULL DEFAULT 'idea',
  priority TEXT NOT NULL DEFAULT 'medium',
  target_date TEXT,
  budget_notes TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT home_projects_status_check CHECK (status IN ('idea', 'planning', 'quoted', 'scheduled', 'complete')),
  CONSTRAINT home_projects_priority_check CHECK (priority IN ('low', 'medium', 'high'))
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'google_drive',
  url TEXT NOT NULL,
  mime_type TEXT,
  category TEXT NOT NULL DEFAULT 'other',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS document_links (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id BIGINT NOT NULL,
  label TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS drive_vehicles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  vehicle_type TEXT NOT NULL DEFAULT 'car',
  seats INTEGER NOT NULL DEFAULT 4,
  cargo_summary TEXT,
  driver_name TEXT,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS drive_loadout_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  label TEXT NOT NULL,
  item_type TEXT NOT NULL DEFAULT 'gear',
  assigned_vehicle_id BIGINT REFERENCES drive_vehicles(id) ON DELETE SET NULL,
  placement TEXT,
  required BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  order_index INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT drive_loadout_items_type_check CHECK (item_type IN ('adult', 'child', 'pet', 'gear', 'vehicle_addon'))
);

-- Normalize document link entity types to avoid collisions between move tasks and home planning tasks.
UPDATE document_links SET entity_type = 'move_task' WHERE entity_type = 'task';

CREATE INDEX IF NOT EXISTS idx_timeline_entries_track_date ON timeline_entries(track_id, date);
CREATE INDEX IF NOT EXISTS idx_planning_tasks_track_status_due ON planning_tasks(track_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_document_links_entity ON document_links(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_room_items_room ON room_items(room_id);
CREATE INDEX IF NOT EXISTS idx_home_projects_status_target_date ON home_projects(status, target_date);
CREATE INDEX IF NOT EXISTS idx_drive_loadout_items_vehicle ON drive_loadout_items(assigned_vehicle_id);

INSERT INTO tracks (key, name, color, icon, order_index)
VALUES
  ('move', 'Move', '#c06b3e', 'calendar', 0),
  ('drive', 'Drive', '#6366f1', 'moon', 1),
  ('home_purchase', 'Home Purchase', '#c06b3e', 'house', 2),
  ('loan', 'Loan', '#1f6b5b', 'banknote', 3),
  ('home_updates', 'Home Updates', '#8c8882', 'hammer', 4)
ON CONFLICT (key) DO NOTHING;
