-- Measured home layout planning
-- Run after supabase-home-planning.sql.

CREATE TABLE IF NOT EXISTS home_floor_plans (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  width_ft NUMERIC NOT NULL DEFAULT 40,
  depth_ft NUMERIC NOT NULL DEFAULT 32,
  ceiling_height_ft NUMERIC,
  blueprint_document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL,
  blueprint_page INTEGER,
  blueprint_image_path TEXT,
  overlay_offset_x_ft NUMERIC,
  overlay_offset_y_ft NUMERIC,
  overlay_width_ft NUMERIC,
  overlay_depth_ft NUMERIC,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT home_floor_plans_width_check CHECK (width_ft > 0),
  CONSTRAINT home_floor_plans_depth_check CHECK (depth_ft > 0)
);

ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_offset_x_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_offset_y_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_width_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_depth_ft NUMERIC;

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS floor_plan_id BIGINT REFERENCES home_floor_plans(id) ON DELETE SET NULL;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_x_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_y_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_width_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_depth_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS ceiling_height_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS shape_points JSONB;

ALTER TABLE room_items ADD COLUMN IF NOT EXISTS width_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS depth_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS height_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS plan_x_ft NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS plan_y_ft NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS rotation_deg NUMERIC;

CREATE INDEX IF NOT EXISTS idx_home_floor_plans_sort ON home_floor_plans(sort_index, level);
CREATE INDEX IF NOT EXISTS idx_rooms_floor_plan ON rooms(floor_plan_id);
CREATE INDEX IF NOT EXISTS idx_room_items_measured_position ON room_items(room_id, plan_x_ft, plan_y_ft);

INSERT INTO home_floor_plans (
  name,
  label,
  level,
  width_ft,
  depth_ft,
  blueprint_page,
  blueprint_image_path,
  overlay_offset_x_ft,
  overlay_offset_y_ft,
  overlay_width_ft,
  overlay_depth_ft,
  notes,
  sort_index
)
VALUES
  ('Basement', 'Basement', 0, 50, 50, NULL, NULL, 0, 0, 50, 50, 'Needs manual measurement; no basement floor-plan sheet was found in the provided blueprint set.', 0),
  ('Main Floor', 'First Floor', 1, 50, 50, 1, '/api/home-blueprint-assets/first-floor', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A1, scale 1/8 inch = 1 foot.', 10),
  ('Second Floor', 'Second Floor', 2, 50, 50, 1, '/api/home-blueprint-assets/second-floor', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A1, scale 1/8 inch = 1 foot.', 20),
  ('Third Floor', 'Third Floor', 3, 50, 50, 2, '/api/home-blueprint-assets/third-floor', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A2, scale 1/8 inch = 1 foot.', 30),
  ('Exterior', 'Exterior', -1, 80, 80, 6, '/api/home-blueprint-assets/site-plan', 0, 0, 80, 80, 'Exterior planning area for garage, porch, and yard items.', 40)
ON CONFLICT (name) DO UPDATE SET
  label = EXCLUDED.label,
  level = EXCLUDED.level,
  width_ft = EXCLUDED.width_ft,
  depth_ft = EXCLUDED.depth_ft,
  blueprint_page = EXCLUDED.blueprint_page,
  blueprint_image_path = EXCLUDED.blueprint_image_path,
  overlay_offset_x_ft = COALESCE(home_floor_plans.overlay_offset_x_ft, EXCLUDED.overlay_offset_x_ft),
  overlay_offset_y_ft = COALESCE(home_floor_plans.overlay_offset_y_ft, EXCLUDED.overlay_offset_y_ft),
  overlay_width_ft = COALESCE(home_floor_plans.overlay_width_ft, EXCLUDED.overlay_width_ft),
  overlay_depth_ft = COALESCE(home_floor_plans.overlay_depth_ft, EXCLUDED.overlay_depth_ft),
  notes = COALESCE(home_floor_plans.notes, EXCLUDED.notes),
  sort_index = EXCLUDED.sort_index;

UPDATE rooms
SET floor_plan_id = home_floor_plans.id
FROM home_floor_plans
WHERE rooms.floor_plan_id IS NULL
  AND rooms.floor = home_floor_plans.name;
