-- Starland Move Tracker — DB Migration
-- Run this in the Supabase SQL editor before deploying the new code.

-- ─────────────────────────────────────────
-- 1. TASKS: remove dead columns, fix completed_at
-- ─────────────────────────────────────────
ALTER TABLE tasks DROP COLUMN IF EXISTS "scheduledEventDate";
ALTER TABLE tasks DROP COLUMN IF EXISTS "scheduledEventTimeWindow";
-- timingType / timingOffsetDays may be stored in several casings
ALTER TABLE tasks DROP COLUMN IF EXISTS timingtype;
ALTER TABLE tasks DROP COLUMN IF EXISTS "timingType";
ALTER TABLE tasks DROP COLUMN IF EXISTS timingoffsetdays;
ALTER TABLE tasks DROP COLUMN IF EXISTS "timingOffsetDays";

-- Rename completionDate → completed_at (or add if missing)
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'tasks' AND column_name = 'completionDate'
  ) THEN
    ALTER TABLE tasks RENAME COLUMN "completionDate" TO completed_at;
  ELSIF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'tasks' AND column_name = 'completed_at'
  ) THEN
    ALTER TABLE tasks ADD COLUMN completed_at TEXT;
  END IF;
END $$;

-- ─────────────────────────────────────────
-- 2. BELONGINGS: rename table, fix status, drop priority
-- ─────────────────────────────────────────
ALTER TABLE packing_items RENAME TO belongings;

-- Normalise existing status values before changing the constraint
UPDATE belongings SET status = 'unresolved'
  WHERE lower(status) IN ('not packed', 'unresolved');
UPDATE belongings SET status = 'resolved'
  WHERE lower(status) IN ('packed', 'resolved');

ALTER TABLE belongings DROP CONSTRAINT IF EXISTS packing_items_status_check;
ALTER TABLE belongings ADD CONSTRAINT belongings_status_check
  CHECK (status IN ('unresolved', 'resolved'));

ALTER TABLE belongings DROP COLUMN IF EXISTS priority;

-- ─────────────────────────────────────────
-- 3. EVENTS: new table for custom timeline events
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT,
  is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);
