-- CREATE TABLES
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  earliest_move_date TEXT NOT NULL,
  latest_move_date TEXT NOT NULL,
  confirmed_move_date TEXT,
  closing_date TEXT,
  is_closing_date_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  upack_dropoff_date TEXT,
  is_upack_dropoff_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  upack_pickup_date TEXT,
  is_upack_pickup_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  drive_start_date TEXT,
  is_drive_start_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  arrival_date TEXT,
  is_arrival_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  upack_delivery_date TEXT,
  is_upack_delivery_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  upack_final_pickup_date TEXT,
  is_upack_final_pickup_confirmed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('Not Started', 'In Progress', 'Complete')),
  owner TEXT NOT NULL CHECK (owner IN ('Andrew', 'Tory', 'Both')),
  phase TEXT NOT NULL DEFAULT 'Both' CHECK (phase IN ('Move Out', 'Move In', 'Both')),
  due_date TEXT,
  completion_date TEXT,
  scheduled_event_date TEXT,
  scheduled_event_time_window TEXT,
  notes TEXT,
  order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS packing_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room TEXT NOT NULL,
  item_name TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('Bring', 'Trash', 'Sell', 'Donate')),
  status TEXT NOT NULL DEFAULT 'Unresolved' CHECK (status IN ('Unresolved', 'Resolved')),
  notes TEXT,
  priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High')),
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  is_link BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  notes TEXT,
  category TEXT NOT NULL CHECK (category IN ('Origin', 'Destination', 'Stop', 'Utility', 'Errand', 'Service')),
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

-- SEED DATA
INSERT INTO settings (id, earliest_move_date, latest_move_date)
VALUES (1, '2026-06-15', '2026-07-01')
ON CONFLICT (id) DO NOTHING;

INSERT INTO categories (name, order_index)
VALUES 
  ('Move-Out Logistics', 0),
  ('Move-In Setup', 1),
  ('Packing & Supplies', 2),
  ('Travel Planning', 3),
  ('Utilities Setup & Cancellation', 4),
  ('Address Changes', 5),
  ('Financial & Banking Updates', 6),
  ('Insurance', 7),
  ('Medical & Pharmacy', 8),
  ('Pets', 9),
  ('Home Purchases & Setup', 10),
  ('Closing & Contract', 11),
  ('Cold Spring Local Setup', 12)
ON CONFLICT DO NOTHING;
