-- Architectural element layer for the measured home layout.
-- Run after supabase-home-planning.sql / supabase-measured-layout.sql.

CREATE TABLE IF NOT EXISTS architectural_elements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  floor_plan_id BIGINT NOT NULL REFERENCES home_floor_plans(id) ON DELETE CASCADE,
  room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
  element_type TEXT NOT NULL DEFAULT 'fixture',
  label TEXT NOT NULL,
  x_ft NUMERIC NOT NULL DEFAULT 0,
  y_ft NUMERIC NOT NULL DEFAULT 0,
  width_ft NUMERIC NOT NULL DEFAULT 1,
  depth_ft NUMERIC NOT NULL DEFAULT 1,
  rotation_deg NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT architectural_elements_type_check CHECK (
    element_type IN ('door', 'window', 'opening', 'stairs', 'counter', 'cabinet', 'sink', 'toilet', 'shower', 'tub', 'appliance', 'fixture')
  ),
  CONSTRAINT architectural_elements_width_check CHECK (width_ft > 0),
  CONSTRAINT architectural_elements_depth_check CHECK (depth_ft > 0)
);

CREATE INDEX IF NOT EXISTS idx_architectural_elements_floor ON architectural_elements(floor_plan_id, sort_index);
CREATE INDEX IF NOT EXISTS idx_architectural_elements_room ON architectural_elements(room_id);
CREATE INDEX IF NOT EXISTS idx_architectural_elements_type ON architectural_elements(element_type);

ALTER TABLE architectural_elements ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  CREATE POLICY "authenticated_full_access" ON architectural_elements
    FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
