-- CREATE TABLES
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  "closingDate" TEXT,
  "isClosingDateConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "upackDropoffDate" TEXT,
  "isUpackDropoffConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "upackPickupDate" TEXT,
  "isUpackPickupConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "driveStartDate" TEXT,
  "isDriveStartConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "arrivalDate" TEXT,
  "isArrivalConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "upackDeliveryDate" TEXT,
  "isUpackDeliveryConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "upackFinalPickupDate" TEXT,
  "isUpackFinalPickupConfirmed" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  "orderIndex" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "categoryId" BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('Not Started', 'In Progress', 'Complete')),
  owner TEXT NOT NULL CHECK (owner IN ('Andrew', 'Tory', 'Both')),
  phase TEXT NOT NULL DEFAULT 'Both' CHECK (phase IN ('Move Out', 'Move In', 'Both')),
  "dueDate" TEXT,
  "completionDate" TEXT,
  "scheduledEventDate" TEXT,
  "scheduledEventTimeWindow" TEXT,
  notes TEXT,
  "orderIndex" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS packing_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room TEXT NOT NULL,
  "itemName" TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('Bring', 'Trash', 'Sell', 'Donate')),
  status TEXT NOT NULL DEFAULT 'Unresolved' CHECK (status IN ('Unresolved', 'Resolved')),
  notes TEXT,
  priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High')),
  "createdAt" TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "taskId" BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  "categoryId" BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  "isLink" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  notes TEXT,
  category TEXT NOT NULL CHECK (category IN ('Origin', 'Destination', 'Stop', 'Utility', 'Errand', 'Service')),
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  "createdAt" TEXT NOT NULL DEFAULT (now())::text
);

-- SEED DATA
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

INSERT INTO categories (name, "orderIndex")
VALUES 
  ('Move-Out Logistics', 0),
  ('Move-In Setup', 1),
  ('Packing & Supplies', 2),
  ('Travel Planning', 3),
  ('Utilities Setup & Cancellation', 4),
  ('Address Changes', 5),
  ('Financial & Banking Updates', 6),
  ('Insurance', 7),
  ('Medical & Pharmacy', 8),
  ('Pets', 9),
  ('Home Purchases & Setup', 10),
  ('Closing & Contract', 11),
  ('Cold Spring Local Setup', 12)
ON CONFLICT DO NOTHING;
