-- Home planning expansion
-- Run after the existing schema + migration scripts.

-- Reconcile task owner to match current app behavior.
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_owner_check;
ALTER TABLE tasks ALTER COLUMN owner DROP NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_owner_check
  CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory'));

-- Replace legacy documents table with a generic attachment model.
DROP TABLE IF EXISTS documents CASCADE;

CREATE TABLE IF NOT EXISTS tracks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  color TEXT,
  icon TEXT,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS timeline_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  entry_type TEXT NOT NULL DEFAULT 'event',
  status TEXT NOT NULL DEFAULT 'estimated',
  date TEXT NOT NULL,
  time TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS planning_tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  section TEXT NOT NULL DEFAULT 'purchase',
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Not Started',
  owner TEXT,
  due_date TEXT,
  completed_at TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT planning_tasks_status_check CHECK (status IN ('Not Started', 'In Progress', 'Blocked', 'Complete')),
  CONSTRAINT planning_tasks_owner_check CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory')),
  CONSTRAINT planning_tasks_section_check CHECK (section IN ('purchase', 'loan', 'home_setup', 'updates'))
);

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  floor TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS room_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  belonging_id BIGINT REFERENCES belongings(id) ON DELETE SET NULL,
  item_name TEXT NOT NULL,
  item_source TEXT NOT NULL DEFAULT 'planned_purchase',
  status TEXT NOT NULL DEFAULT 'planned',
  dimensions TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT room_items_source_check CHECK (item_source IN ('existing_belonging', 'planned_purchase')),
  CONSTRAINT room_items_status_check CHECK (status IN ('planned', 'placed', 'undecided'))
);

ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_x NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_y NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_w NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS layout_h NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS width_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS depth_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS height_in NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS plan_x_ft NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS plan_y_ft NUMERIC;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS rotation_deg NUMERIC;

CREATE TABLE IF NOT EXISTS home_projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  area TEXT,
  status TEXT NOT NULL DEFAULT 'idea',
  priority TEXT NOT NULL DEFAULT 'medium',
  target_date TEXT,
  budget_notes TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT home_projects_status_check CHECK (status IN ('idea', 'planning', 'quoted', 'scheduled', 'complete')),
  CONSTRAINT home_projects_priority_check CHECK (priority IN ('low', 'medium', 'high'))
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'google_drive',
  url TEXT NOT NULL,
  url_key TEXT,
  mime_type TEXT,
  category TEXT NOT NULL DEFAULT 'other',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS home_floor_plans (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  width_ft NUMERIC NOT NULL DEFAULT 40,
  depth_ft NUMERIC NOT NULL DEFAULT 32,
  ceiling_height_ft NUMERIC,
  blueprint_document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL,
  blueprint_page INTEGER,
  blueprint_image_path TEXT,
  overlay_offset_x_ft NUMERIC,
  overlay_offset_y_ft NUMERIC,
  overlay_width_ft NUMERIC,
  overlay_depth_ft NUMERIC,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT home_floor_plans_width_check CHECK (width_ft > 0),
  CONSTRAINT home_floor_plans_depth_check CHECK (depth_ft > 0)
);

ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_offset_x_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_offset_y_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_width_ft NUMERIC;
ALTER TABLE home_floor_plans ADD COLUMN IF NOT EXISTS overlay_depth_ft NUMERIC;

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS floor_plan_id BIGINT REFERENCES home_floor_plans(id) ON DELETE SET NULL;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_x_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_y_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_width_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS plan_depth_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS ceiling_height_ft NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS shape_points JSONB;
ALTER TABLE room_items ADD COLUMN IF NOT EXISTS floor_plan_id BIGINT REFERENCES home_floor_plans(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS document_links (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id BIGINT NOT NULL,
  label TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS drive_vehicles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  vehicle_type TEXT NOT NULL DEFAULT 'car',
  seats INTEGER NOT NULL DEFAULT 4,
  cargo_summary TEXT,
  driver_name TEXT,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS drive_loadout_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  label TEXT NOT NULL,
  item_type TEXT NOT NULL DEFAULT 'gear',
  assigned_vehicle_id BIGINT REFERENCES drive_vehicles(id) ON DELETE SET NULL,
  placement TEXT,
  required BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  order_index INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT drive_loadout_items_type_check CHECK (item_type IN ('adult', 'child', 'pet', 'gear', 'vehicle_addon'))
);

-- Normalize document link entity types to avoid collisions between move tasks and home planning tasks.
UPDATE document_links SET entity_type = 'move_task' WHERE entity_type = 'task';

CREATE INDEX IF NOT EXISTS idx_timeline_entries_track_date ON timeline_entries(track_id, date);
CREATE INDEX IF NOT EXISTS idx_planning_tasks_track_status_due ON planning_tasks(track_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_document_links_entity ON document_links(entity_type, entity_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_documents_url_key_unique ON documents(url_key) WHERE url_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_document_links_unique_entity ON document_links(document_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_room_items_room ON room_items(room_id);
CREATE INDEX IF NOT EXISTS idx_home_floor_plans_sort ON home_floor_plans(sort_index, level);
CREATE INDEX IF NOT EXISTS idx_rooms_floor_plan ON rooms(floor_plan_id);
CREATE INDEX IF NOT EXISTS idx_room_items_floor_plan ON room_items(floor_plan_id);
CREATE INDEX IF NOT EXISTS idx_room_items_measured_position ON room_items(room_id, plan_x_ft, plan_y_ft);
CREATE INDEX IF NOT EXISTS idx_home_projects_status_target_date ON home_projects(status, target_date);
CREATE INDEX IF NOT EXISTS idx_drive_loadout_items_vehicle ON drive_loadout_items(assigned_vehicle_id);

INSERT INTO tracks (key, name, color, icon, order_index)
VALUES
  ('move', 'Move', '#c06b3e', 'calendar', 0),
  ('drive', 'Drive', '#6366f1', 'moon', 1),
  ('home_purchase', 'Home Purchase', '#c06b3e', 'house', 2),
  ('loan', 'Loan', '#1f6b5b', 'banknote', 3),
  ('home_updates', 'Home Updates', '#8c8882', 'hammer', 4)
ON CONFLICT (key) DO NOTHING;

INSERT INTO home_floor_plans (
  name,
  label,
  level,
  width_ft,
  depth_ft,
  blueprint_page,
  blueprint_image_path,
  overlay_offset_x_ft,
  overlay_offset_y_ft,
  overlay_width_ft,
  overlay_depth_ft,
  notes,
  sort_index
)
VALUES
  ('Basement', 'Basement', 0, 50, 50, NULL, NULL, 0, 0, 50, 50, 'Needs manual measurement; no basement floor-plan sheet was found in the provided blueprint set.', 0),
  ('Main Floor', 'First Floor', 1, 50, 50, 1, '/blueprints/first-floor.png', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A1, scale 1/8 inch = 1 foot.', 10),
  ('Second Floor', 'Second Floor', 2, 50, 50, 1, '/blueprints/second-floor.png', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A1, scale 1/8 inch = 1 foot.', 20),
  ('Third Floor', 'Third Floor', 3, 50, 50, 2, '/blueprints/third-floor.png', 0, 0, 50, 50, 'Initial calibration from blueprint sheet A2, scale 1/8 inch = 1 foot.', 30),
  ('Exterior', 'Exterior', -1, 80, 80, 6, '/blueprints/site-plan.png', 0, 0, 80, 80, 'Exterior planning area for garage, porch, and yard items.', 40)
ON CONFLICT (name) DO UPDATE SET
  label = EXCLUDED.label,
  level = EXCLUDED.level,
  width_ft = EXCLUDED.width_ft,
  depth_ft = EXCLUDED.depth_ft,
  blueprint_page = EXCLUDED.blueprint_page,
  blueprint_image_path = EXCLUDED.blueprint_image_path,
  overlay_offset_x_ft = COALESCE(home_floor_plans.overlay_offset_x_ft, EXCLUDED.overlay_offset_x_ft),
  overlay_offset_y_ft = COALESCE(home_floor_plans.overlay_offset_y_ft, EXCLUDED.overlay_offset_y_ft),
  overlay_width_ft = COALESCE(home_floor_plans.overlay_width_ft, EXCLUDED.overlay_width_ft),
  overlay_depth_ft = COALESCE(home_floor_plans.overlay_depth_ft, EXCLUDED.overlay_depth_ft),
  notes = COALESCE(home_floor_plans.notes, EXCLUDED.notes),
  sort_index = EXCLUDED.sort_index;

UPDATE rooms
SET floor_plan_id = home_floor_plans.id
FROM home_floor_plans
WHERE rooms.floor_plan_id IS NULL
  AND rooms.floor = home_floor_plans.name;

UPDATE room_items
SET floor_plan_id = rooms.floor_plan_id
FROM rooms
WHERE room_items.floor_plan_id IS NULL
  AND room_items.room_id = rooms.id
  AND rooms.floor_plan_id IS NOT NULL;
