-- Home planning expansion
-- Run after the existing schema + migration scripts.

-- Reconcile task owner to match current app behavior.
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_owner_check;
ALTER TABLE tasks ALTER COLUMN owner DROP NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_owner_check
  CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory'));

-- Replace legacy documents table with a generic attachment model.
DROP TABLE IF EXISTS documents CASCADE;

CREATE TABLE IF NOT EXISTS tracks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  color TEXT,
  icon TEXT,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS timeline_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  entry_type TEXT NOT NULL DEFAULT 'event',
  status TEXT NOT NULL DEFAULT 'estimated',
  date TEXT NOT NULL,
  time TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS planning_tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  track_id BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  section TEXT NOT NULL DEFAULT 'purchase',
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Not Started',
  owner TEXT,
  due_date TEXT,
  completed_at TEXT,
  notes TEXT,
  sort_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now())::text,
  CONSTRAINT planning_tasks_status_check CHECK (status IN ('Not Started', 'In Progress', 'Complete')),
  CONSTRAINT planning_tasks_owner_check CHECK (owner IS NULL OR owner IN ('Andrew', 'Tory')),
  CONSTRAINT planning_tasks_section_check CHECK (section IN ('purchase', 'loan', 'home_setup', 'updates'))
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'google_drive',
  url TEXT NOT NULL,
  mime_type TEXT,
  category TEXT NOT NULL DEFAULT 'other',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE TABLE IF NOT EXISTS document_links (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id BIGINT NOT NULL,
  label TEXT,
  created_at TEXT NOT NULL DEFAULT (now())::text
);

CREATE INDEX IF NOT EXISTS idx_timeline_entries_track_date ON timeline_entries(track_id, date);
CREATE INDEX IF NOT EXISTS idx_planning_tasks_track_status_due ON planning_tasks(track_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_document_links_entity ON document_links(entity_type, entity_id);

INSERT INTO tracks (key, name, color, icon, order_index)
VALUES
  ('move', 'Move', '#c06b3e', 'calendar', 0),
  ('drive', 'Drive', '#6366f1', 'moon', 1),
  ('home_purchase', 'Home Purchase', '#c06b3e', 'house', 2),
  ('loan', 'Loan', '#1f6b5b', 'banknote', 3),
  ('home_updates', 'Home Updates', '#8c8882', 'hammer', 4)
ON CONFLICT (key) DO NOTHING;
